# Generated by Django 5.0.4 on 2024-11-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=500)),
                ('home_team_id', models.CharField(max_length=500)),
                ('away_team_id', models.CharField(max_length=500)),
                ('run_time', models.CharField(max_length=500)),
                ('winning_team_id', models.CharField(max_length=500)),
                ('losing_team_id', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=500)),
                ('team_name', models.CharField(max_length=500)),
            ],
        ),
    ]
