# Generated by Django 5.0.4 on 2024-11-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
