# Generated by Django 5.0.4 on 2024-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
