# Generated by Django 5.0.4 on 2024-11-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_away_score_game_home_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
    ]
