# Generated by Django 5.0.4 on 2024-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_game_id_remove_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='losing_team',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.CharField(default='', max_length=500),
        ),
    ]
